"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_local_env():
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return
    for raw in env_path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


_load_local_env()


def _parse_postgres_database_url(url: str) -> dict:
    """Parse postgres/postgresql URLs; supports @ and : inside the password.

    urllib.parse.urlparse breaks when the password contains unencoded '@'.
    """
    url = url.strip()
    if not url.startswith(("postgres://", "postgresql://")):
        raise ValueError("DATABASE_URL must start with postgres:// or postgresql://")
    _, rest = url.split("://", 1)
    if "?" in rest:
        rest, _query = rest.split("?", 1)
    if "@" not in rest:
        raise ValueError("DATABASE_URL must include user:password@host")
    userinfo, host_and_db = rest.rsplit("@", 1)
    if ":" not in userinfo:
        raise ValueError("DATABASE_URL must include user:password")
    user, password = userinfo.split(":", 1)
    user = unquote(user)
    password = unquote(password)
    if "/" not in host_and_db:
        raise ValueError("DATABASE_URL must include a database name path")
    host_port, _, db_path = host_and_db.partition("/")
    name = unquote(db_path.split("/")[0])
    if ":" in host_port:
        host, port = host_port.rsplit(":", 1)
    else:
        host, port = host_port, "5432"
    host = unquote(host)
    return {
        "NAME": name,
        "USER": user,
        "PASSWORD": password,
        "HOST": host,
        "PORT": port,
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in {'1', 'true', 'yes', 'on'}

_allowed_hosts_raw = os.getenv("ALLOWED_HOSTS", "").strip()
if _allowed_hosts_raw:
    ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts_raw.split(",") if host.strip()]
else:
    ALLOWED_HOSTS = ["*"] if DEBUG else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'categories',
    'planner',
    'transactions',
    'goals',
    'reminders',
]

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
CURRENCY_API_KEY = os.getenv('CURRENCY_API_KEY', '')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_BOT_USERNAME = os.getenv('TELEGRAM_BOT_USERNAME', 'moliyaYordam_bot')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_database_url = os.getenv("DATABASE_URL", "").strip()
if _database_url:
    _db_parts = _parse_postgres_database_url(_database_url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": _db_parts["NAME"],
            "USER": _db_parts["USER"],
            "PASSWORD": _db_parts["PASSWORD"],
            "HOST": _db_parts["HOST"],
            "PORT": str(_db_parts["PORT"]),
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
            "OPTIONS": {
                "sslmode": os.getenv("DB_SSLMODE", "require"),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"



AUTH_USER_MODEL = 'users.User'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# settings.py


# 2. Lokalizatsiyani o'chirish (o'z formatimizni majburlash uchun)
USE_L10N = False

# 3. Vaqt formati (24 soatlik: 14:30 ko'rinishida)
TIME_FORMAT = 'H:i'

# 4. Sana va vaqt birga kelgandagi format
DATE_FORMAT = 'd.m.Y'
DATETIME_FORMAT = 'd.m.Y H:i'

# 5. Formalar (Input) qabul qiladigan formatlar ro'yxati
TIME_INPUT_FORMATS = [
    '%H:%M',        # 14:30
    '%H:%M:%S',     # 14:30:59
]

DATE_INPUT_FORMATS = [
    '%d/%m/%Y',     # 17/04/2026
    '%d.%m.%Y',     # 17.04.2026
    '%Y-%m-%d',     # 2026-04-17
    '%m/%d/%Y',     # 04/17/2026
    '%m/%d/%y',     # 04/17/26
]

DATETIME_INPUT_FORMATS = [
    '%d/%m/%Y %H:%M',     # 17/04/2026 14:30
    '%d.%m.%Y %H:%M',     # 17.04.2026 14:30
    '%Y-%m-%d %H:%M:%S',   # 2026-04-17 14:30:59
    '%Y-%m-%d %H:%M',      # 2026-04-17 14:30
]

LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'users:login'

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_STT_MODEL = os.getenv("OPENAI_STT_MODEL", "gpt-4o-transcribe")